// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: proto/draw.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiRectangleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     string                            `protobuf:"bytes,1,opt,name=Image,proto3" json:"Image,omitempty"`
	Title     string                            `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Rectangle []*MultiRectangleRequestRectangle `protobuf:"bytes,3,rep,name=Rectangle,proto3" json:"Rectangle,omitempty"`
}

func (x *MultiRectangleRequest) Reset() {
	*x = MultiRectangleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_draw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiRectangleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRectangleRequest) ProtoMessage() {}

func (x *MultiRectangleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRectangleRequest.ProtoReflect.Descriptor instead.
func (*MultiRectangleRequest) Descriptor() ([]byte, []int) {
	return file_proto_draw_proto_rawDescGZIP(), []int{0}
}

func (x *MultiRectangleRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MultiRectangleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MultiRectangleRequest) GetRectangle() []*MultiRectangleRequestRectangle {
	if x != nil {
		return x.Rectangle
	}
	return nil
}

type MultiRectangleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string                      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MultiRectangleResponseData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *MultiRectangleResponse) Reset() {
	*x = MultiRectangleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_draw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiRectangleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRectangleResponse) ProtoMessage() {}

func (x *MultiRectangleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRectangleResponse.ProtoReflect.Descriptor instead.
func (*MultiRectangleResponse) Descriptor() ([]byte, []int) {
	return file_proto_draw_proto_rawDescGZIP(), []int{1}
}

func (x *MultiRectangleResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MultiRectangleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MultiRectangleResponse) GetData() *MultiRectangleResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MultiRectangleRequestRectangle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	W int32 `protobuf:"varint,3,opt,name=W,proto3" json:"W,omitempty"`
	H int32 `protobuf:"varint,4,opt,name=H,proto3" json:"H,omitempty"`
}

func (x *MultiRectangleRequestRectangle) Reset() {
	*x = MultiRectangleRequestRectangle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_draw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiRectangleRequestRectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRectangleRequestRectangle) ProtoMessage() {}

func (x *MultiRectangleRequestRectangle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRectangleRequestRectangle.ProtoReflect.Descriptor instead.
func (*MultiRectangleRequestRectangle) Descriptor() ([]byte, []int) {
	return file_proto_draw_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MultiRectangleRequestRectangle) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MultiRectangleRequestRectangle) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MultiRectangleRequestRectangle) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *MultiRectangleRequestRectangle) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type MultiRectangleResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string `protobuf:"bytes,1,opt,name=Image,proto3" json:"Image,omitempty"`
}

func (x *MultiRectangleResponseData) Reset() {
	*x = MultiRectangleResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_draw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiRectangleResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRectangleResponseData) ProtoMessage() {}

func (x *MultiRectangleResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRectangleResponseData.ProtoReflect.Descriptor instead.
func (*MultiRectangleResponseData) Descriptor() ([]byte, []int) {
	return file_proto_draw_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MultiRectangleResponseData) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_proto_draw_proto protoreflect.FileDescriptor

var file_proto_draw_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xcb, 0x01, 0x0a, 0x15, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x41, 0x0a, 0x09,
	0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x72, 0x65, 0x63, 0x74, 0x61,
	0x6e, 0x67, 0x6c, 0x65, 0x52, 0x09, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x1a,
	0x43, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x12, 0x0c, 0x0a, 0x01, 0x57, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x57, 0x12, 0x0c, 0x0a, 0x01, 0x48, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x48, 0x22, 0x99, 0x01, 0x0a, 0x16, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65,
	0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x1c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x32, 0x51, 0x0a, 0x04, 0x44, 0x72, 0x61, 0x77, 0x12, 0x49, 0x0a, 0x0e, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_draw_proto_rawDescOnce sync.Once
	file_proto_draw_proto_rawDescData = file_proto_draw_proto_rawDesc
)

func file_proto_draw_proto_rawDescGZIP() []byte {
	file_proto_draw_proto_rawDescOnce.Do(func() {
		file_proto_draw_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_draw_proto_rawDescData)
	})
	return file_proto_draw_proto_rawDescData
}

var file_proto_draw_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_draw_proto_goTypes = []interface{}{
	(*MultiRectangleRequest)(nil),          // 0: pb.MultiRectangleRequest
	(*MultiRectangleResponse)(nil),         // 1: pb.MultiRectangleResponse
	(*MultiRectangleRequestRectangle)(nil), // 2: pb.MultiRectangleRequest.rectangle
	(*MultiRectangleResponseData)(nil),     // 3: pb.MultiRectangleResponse.data
}
var file_proto_draw_proto_depIdxs = []int32{
	2, // 0: pb.MultiRectangleRequest.Rectangle:type_name -> pb.MultiRectangleRequest.rectangle
	3, // 1: pb.MultiRectangleResponse.Data:type_name -> pb.MultiRectangleResponse.data
	0, // 2: pb.Draw.MultiRectangle:input_type -> pb.MultiRectangleRequest
	1, // 3: pb.Draw.MultiRectangle:output_type -> pb.MultiRectangleResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_draw_proto_init() }
func file_proto_draw_proto_init() {
	if File_proto_draw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_draw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiRectangleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_draw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiRectangleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_draw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiRectangleRequestRectangle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_draw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiRectangleResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_draw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_draw_proto_goTypes,
		DependencyIndexes: file_proto_draw_proto_depIdxs,
		MessageInfos:      file_proto_draw_proto_msgTypes,
	}.Build()
	File_proto_draw_proto = out.File
	file_proto_draw_proto_rawDesc = nil
	file_proto_draw_proto_goTypes = nil
	file_proto_draw_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DrawClient is the client API for Draw service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrawClient interface {
	MultiRectangle(ctx context.Context, in *MultiRectangleRequest, opts ...grpc.CallOption) (*MultiRectangleResponse, error)
}

type drawClient struct {
	cc grpc.ClientConnInterface
}

func NewDrawClient(cc grpc.ClientConnInterface) DrawClient {
	return &drawClient{cc}
}

func (c *drawClient) MultiRectangle(ctx context.Context, in *MultiRectangleRequest, opts ...grpc.CallOption) (*MultiRectangleResponse, error) {
	out := new(MultiRectangleResponse)
	err := c.cc.Invoke(ctx, "/pb.Draw/MultiRectangle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrawServer is the server API for Draw service.
type DrawServer interface {
	MultiRectangle(context.Context, *MultiRectangleRequest) (*MultiRectangleResponse, error)
}

// UnimplementedDrawServer can be embedded to have forward compatible implementations.
type UnimplementedDrawServer struct {
}

func (*UnimplementedDrawServer) MultiRectangle(context.Context, *MultiRectangleRequest) (*MultiRectangleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiRectangle not implemented")
}

func RegisterDrawServer(s *grpc.Server, srv DrawServer) {
	s.RegisterService(&_Draw_serviceDesc, srv)
}

func _Draw_MultiRectangle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiRectangleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServer).MultiRectangle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Draw/MultiRectangle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServer).MultiRectangle(ctx, req.(*MultiRectangleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Draw_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Draw",
	HandlerType: (*DrawServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MultiRectangle",
			Handler:    _Draw_MultiRectangle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/draw.proto",
}
